### ISSUE TITLE
Lambda Parallelization Factor

### ISSUE THREAD

**Issue by lammedon** [awslabs/amazon-kinesis-scaling-utils#84] opened 2020-04-03 18:44 UTC
We use Lambda functions fed by Kinesis in our architecture.  
 
This app monitors throughput for Kinesis (number of records, amount of data) via CloudWatch. In addition to this it would be good to monitor lambda performance via the CloudWatch metric IteratorAge to scale the relatively new parameter in Kinesis/Lamba, "parallelization factor".

https://aws.amazon.com/about-aws/whats-new/2019/11/aws-lambda-supports-parallelization-factor-for-kinesis-and-dynamodb-event-sources/

**Comment by IanMeyers** [comment] 2020-06-09 15:46
That does sound useful. Will look into it and see how hard it will be to do. Would need to bound to a single application however, which could be unpredictable.

**Comment by IanMeyers** [comment] 2020-12-11 13:52
Closing as duplicate of #63

**Closed by IanMeyers** 2020-12-11 13:52 UTC
